name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main , develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4
        
      - name: PHP環境のセットアップ
        uses: shivammathur/setup-php@v2
        with:
            php-version: '8.3'
            extensions: mbstring, xml, ctype, json, pdo, mysql
            
      - name: Composerの依存関係をインストール
        run: composer install --prefer-dist --no-progress

      - name: .envファイルの作成
        run: |
          cp .env.example .env
          php artisan key:generate

          -name; テスト実行
          run: php artisan test
          


