name: Tests

on: [push, pull_request]

jobs:
test:
runs-on: ubuntu-latest

services:
mysql:
image: mysql:8.0
env.
MYSQL_ROOT_PASSWORD: password
MYSQL_DATABASE:testing
ports:
- 3306:3306
options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3s

steps:
- use: actions/checkout@v4

- name:Setup PHP
users: shivammathur/setup-php@v2
with: 
php-version: '8.3'
extensions: mbstring, xml, ctype, json, pdo,mysql

- name: Install dependencies
run: composer install

- name: Copy .env
run: |
cp .env.example .env
php artisankey:generate

- name: Run migrations
env:
DB_CONNECTION: mysql
DB_HOST:127.0.0.1
DB_PORT: 3306
DB_DATABASE: testing
DB_USERNAME: root
DB_PASSWORD: password
run: php artisan migtate

- name: Run tests
env:
DB_CONNECTION: mysql
DB_HOST:127.0.0.1
DB_PORT: 3306
DB_DATABASE:testing
DB_USERNAME: root
DB_PASSSWORD: password
run: php artisan test --coverage


