name: Lint

on: [push, pull_request]

defaults:
  run:
    working-directory: myapp

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup php
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'

            - name: Install dependencies
              run: composer install

            - name: Run PHP CS Fixer
              run: vendor/bin/php-cs-fixer fix --dry-run --diff

    phpstan:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.5.5'

            - name: Install dependencies
              run: composer install

            - name: Run PHPStan
              run: vendor/bin/phpstan analyse --memory-limit=1G

